### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-3-TsurikovDmitriy** [UMSF-K13-3-TsurikovDmitriy/K13-3-TsurikovDmitriy-MainProject#2]

**Comment by UMSF-K13-3-TsurikovDmitriy** [comment]
Скрин добавления файла проекта:
![1](https://cloud.githubusercontent.com/assets/19708667/15770537/2ed7ca7e-296d-11e6-9947-01b39323065d.JPG)

**Comment by Smoktii** [comment]
Ok
